services:
  - type: web
    name: pracky-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 4
    healthCheckPath: /api/whatsapp
    envVars:
      - key: DOWNLOAD_FOLDER
        value: /var/data/downloads